/*
Operadores lógicos

    && -> AND -> E : TODAS AS EXPRESSÕES PRECISAM SER 'TRUE' PARA RETORNAR 'TRUE'
    || -> OR -> OU : APENAS UMA DAS EXPERESSÕES PRECISA SER 'TRUE' PARA RETORNAR 'TRUE'
    ! -> NOT -> NÃO , NEGAÇÃO : INVERTE 'TRUE' PARA 'FALSE' E VICE-VERSA

*/

